server:
  port: 9002
spring:  
 profiles: dev
 datasource:
    url: jdbc:mysql://localhost:3306/logiware_rates
    username: root
    password: L0g!w@r3
 jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true
        id:
          new_generator_mappings: false
 spring:  
  profiles: prd